// <auto-generated />
using EFCoreInheritanceSample.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCoreInheritanceSample.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    partial class AnimalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCoreInheritanceSample.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Animals_Name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Animals_ParentId");

                    b.ToTable("Animals");

                    b.HasDiscriminator().HasValue("Animal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EFCoreInheritanceSample.Entities.Cat", b =>
                {
                    b.HasBaseType("EFCoreInheritanceSample.Entities.Animal");

                    b.Property<int>("MiceCaughtCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Cat");
                });

            modelBuilder.Entity("EFCoreInheritanceSample.Entities.Dog", b =>
                {
                    b.HasBaseType("EFCoreInheritanceSample.Entities.Animal");

                    b.Property<int>("BonesBuriedCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Dog");
                });

            modelBuilder.Entity("EFCoreInheritanceSample.Entities.Animal", b =>
                {
                    b.HasOne("EFCoreInheritanceSample.Entities.Animal", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EFCoreInheritanceSample.Entities.Animal", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
